/* Chapter 5 exercise 23 */

/* n_0을 주어진 양의 정수라 하자. 이때 n_{i+1}은, i = 0, 1, 2, ...에 대하여, 다음과 같
 * 이 정의된다.

    n_i가 짝수이면, n_{i+1} = n_i / 2
    홀수이면, n_{i+1} = 3n_i + 1

 * 이 수열은 n_i 값이 1일 때 멈추게 된다. 이런 방법으로 생성되는 수를 "hailstones"라고
 * 한다. hailstones를 생성하는 프로그램을 작성하여라. 함수 헤드는 다음과 같다.

    void hailstones(int n)
    {
        .....

 * 이 함수는 n에 의해 생성되는 수열을 계산하고 출력해야 한다. 예를 들면, 이 프로그램의 출
 * 력은 다음과 같은 형태이어야 한다.
 
    Hailstones generated by 77 :
        77      232     116     58      29      88
        44      22      11      34      17      52
        26      13      40      20      10      5
        16      8       4       2       1

    Number of hailstones generated : 23

 * 생성되는 모든 수열은 유한함을 알 수 있다. 일반적으로 이것이 참인지는 미해결 문제이다.
 */

#include <stdio.h>

void hailstones(int n);

int main(void)
{
    int n;
    printf("Input positive integer: ");
    scanf("%d", &n);
    hailstones(n);
    return 0;
}

void hailstones(int n)
{
    int cnt = 0;

    printf("Hailstones generated by %d :\n", n);

    while (n != 1)
    {
        printf("%5d", n);
        if (n % 2 == 0){
            n /= 2;
        }
        else {
            n = 3*n + 1;
        }
        cnt++;

        if (cnt % 6 == 0){
            putchar('\n');
        }
    }
    printf("%5d", n);
    cnt++;

    putchar('\n');
    printf("Number of hailstones generated : %d\n", cnt);
}